"""Hardware seam used by the control logic and its test adapter."""

from __future__ import annotations

from typing import Any, Literal, Protocol

MotorPort = Literal["A", "B", "C"]
SensorPort = Literal[1, 2, 3, 4]
SensorType = Literal["touch", "light", "sound", "ultrasonic", "color", "temperature"]


class NxtHardware(Protocol):
    def brick_info(self) -> dict[str, Any]: ...

    def run_motor(self, port: MotorPort, power: int, regulated: bool = True) -> None: ...

    def stop_motor(self, port: MotorPort, brake: bool = False) -> None: ...

    def turn_motor(
        self, port: MotorPort, power: int, ticks: int, brake: bool, timeout_seconds: float
    ) -> None: ...

    def reset_motor_position(self, port: MotorPort) -> None: ...

    def run_motors(
        self, movements: list[tuple[MotorPort, int]], regulated: bool = True
    ) -> None: ...

    def stop_motors(self, ports: list[MotorPort], brake: bool = False) -> None: ...

    def turn_motors(
        self,
        movements: list[tuple[MotorPort, int, int]],
        brake: bool,
        timeout_seconds: float,
    ) -> None: ...

    def motor_state(self, port: MotorPort) -> dict[str, Any]: ...

    def read_sensor(self, port: SensorPort, sensor_type: SensorType) -> dict[str, Any]: ...

    def snapshot(self) -> dict[str, Any]: ...

    def emergency_stop(self) -> None: ...

    def start_program(self, name: str) -> None: ...

    def stop_program(self) -> None: ...

    def current_program(self) -> str | None: ...

    def play_tone(self, frequency_hz: int, duration_ms: int) -> None: ...

    def close(self) -> None: ...
